[package]
name = "wtf-is"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "I was tired of looking up Metaplex program errors."
repository = "https://github.com/samuelvanderwaal/wtf-is"

[dependencies]
phf = { version = "0.10", features = ["macros"] }